server:
  port: 9090
  forward-headers-strategy: framework  # <-- a nivel raíz

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # === Auth (público) ===
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # === INTERNET: DOCS/H2 PÚBLICO (debe ir ANTES que el protegido) ===
        - id: ms-internet-docs
          uri: lb://ms-internet
          predicates:
            # múltiples patrones en UNA sola entrada Path, separados por coma (sin espacios)
            - Path=/internet/v3/api-docs,/internet/doc/**,/internet/h2-console/**
          filters:
            - StripPrefix=1

        # === INTERNET: PROTEGIDO ===
        - id: ms-internet
          uri: lb://ms-internet
          predicates:
            - Path=/internet/**
          filters:
            - StripPrefix=1
            - AuthFilter   # exige JWT

        # === PAGO: DOCS/H2 PÚBLICO (antes que protegido) ===
        - id: ms-pago-docs
          uri: lb://ms-pago
          predicates:
            - Path=/pago/v3/api-docs,/pago/doc/**,/pago/h2-console/**
          filters:
            - StripPrefix=1

        # === PAGO: PROTEGIDO ===
        - id: ms-pago
          uri: lb://ms-pago
          predicates:
            - Path=/pago/**
          filters:
            - StripPrefix=1
            - AuthFilter

# Opcional: agregar agregador de Swagger en el gateway (si usas springdoc webflux en el gateway)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    urls:
      - name: ms-internet
        url: /internet/v3/api-docs
      - name: ms-pago
        url: /pago/v3/api-docs
      - name: ms-auth
        url: /auth/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
