server:
  port: 9090

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # === Auth (público) ===
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # === INTERNET: DOCS/H2 PÚBLICO ===
        - id: ms-internet-docs
          uri: lb://ms-internet
          predicates:
            - Path=/internet/v3/api-docs, /internet/doc/**, /internet/h2-console/**
          filters:
            - StripPrefix=1

        # === INTERNET: PROTEGIDO ===
        - id: ms-internet
          uri: lb://ms-internet
          predicates:
            - Path=/internet/**
          filters:
            - StripPrefix=1
            - AuthFilter   # <- se exige JWT aquí

        # === PAGO: DOCS PÚBLICO ===
        - id: ms-pago-docs
          uri: lb://ms-pago
          predicates:
            - Path=/pago/v3/api-docs, /pago/doc/**, /pago/h2-console/**
          filters:
            - StripPrefix=1

        # === PAGO: PROTEGIDO ===
        - id: ms-pago
          uri: lb://ms-pago
          predicates:
            - Path=/pago/**
          filters:
            - StripPrefix=1
            - AuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
