server:
  port: 9090

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false   # evita rutas auto /ms-.../**
      routes:
        # === Auth (público) ===
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # === Internet (prefijo /internet) ===
        - id: ms-internet
          uri: lb://ms-internet
          predicates:
            - Path=/internet/**
          filters:
            - StripPrefix=1   # /internet/** -> /** en ms-internet

        # === Pago (prefijo /pago) ===
        - id: ms-pago
          uri: lb://ms-pago
          predicates:
            - Path=/pago/**
          filters:
            - StripPrefix=1   # /pago/** -> /** en ms-pago

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# 📚 Agregador Swagger del Gateway (OJO: bloque a nivel raíz)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: ms-internet
        url: /internet/v3/api-docs
      - name: ms-pago
        url: /pago/v3/api-docs
      - name: ms-auth
        url: /auth/v3/api-docs

# (Opcional) Actuators para monitoreo rápido
management:
  endpoints:
    web:
      exposure:
        include: health,info
