server:
  port: 9090

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

      routes:
        # === Auth (público) ===
        - id: ms-auth-route
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**


        # === Internet (protegido) ===
        - id: ms-internet
          uri: lb://ms-internet
          predicates:
            - Path=/clientes/**
            - Path=/maquinas/**
            - Path=/sesiones/**


        # === Pago (protegido) ===
        - id: ms-pago
          uri: lb://ms-pago
          predicates:
            - Path=/metodos-pago/**
            - Path=/pagos/**


