server:
  port: 9090

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}

  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true

      routes:
        # === Auth (público) ===
        - id: ms-auth-route
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**


        # === Internet (protegido) ===
        - id: ms-internet-route
          uri: lb://ms-internet
          predicates:
            - Path=/internet/**
            - Path=/clientes/**
            - Path=/maquinas/**
            - Path=/sesiones/**
          filters:
            - AuthFilter

        # === Pago (protegido) ===
        - id: ms-pago-route
          uri: lb://ms-pago
          predicates:
            - Path=/pago/**
            - Path=/metodos-pago/**
            - Path=/pagos/**
          filters:
            - AuthFilter


        # === Endpoints públicos comunes (swagger/h2) sin Auth ===
        - id: swagger-ui
          uri: no://op
          predicates:
            - Path=/doc/swagger-ui.html
          filters:
            - SetPath=/doc/swagger-ui.html

        - id: api-docs
          uri: no://op
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - SetPath=/v3/api-docs

        - id: h2-console
          uri: no://op
          predicates:
            - Path=/h2-console/**
          filters:
            - SetPath=/h2-console

resilience4j:
  circuitbreaker:
    instances:
      internetCB:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      pagoCB:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
